Quitting if fetch fails

diff --git a/gitup b/gitup
--- a/gitup
+++ b/gitup
@@ -12,6 +12,11 @@ gitup(){
 
 	echo "Fetching..."
 	git fetch --all --prune &>/dev/null
+	if [ $? -ne 0 ]; then
+		echo "Fetch Failed!"
+		return 1
+	fi
+
 	for branch in `git for-each-ref --format='%(refname:short)' refs/heads`; do
 
 		LOCAL=$(git rev-parse --quiet --verify $branch)
